# Generated by Django 4.2.3 on 2023-08-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor', models.CharField(max_length=100)),
                ('xizmat', models.CharField(max_length=100)),
                ('narxlar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kilinikalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.bulimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Shifokorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('qavat', models.IntegerField()),
                ('info', models.TextField()),
                ('ish_kunlari', models.CharField(max_length=100)),
                ('ish_vaqt', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('bulim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.bulimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Navbatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.shifokorlar')),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.xizmatlar')),
            ],
        ),
    ]
