# Generated by Django 4.2.3 on 2023-08-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbatlar',
            name='navbat_raqam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tashxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mulohoza', models.CharField(max_length=100)),
                ('narx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.narxlar')),
                ('navbat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.navbatlar')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.shifokorlar')),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.xizmatlar')),
            ],
        ),
    ]
